#!/bin/bash

##  Script to compile and install libSUFR
##    for gfortran, g95 and ifort.
##  Build in ../usr/, install and clean afterwards
##  AF, 2010

make_gfortran=1
make_g95=1
make_ifort=1

clean_at_end=0


CMAKE_OPTS="-DSTOP_ON_WARNING=on -DCOMPILER_SPECIFIC_LIBS=on -DCREATE_VERSION=on -DCMAKE_INSTALL_PREFIX:PATH=/home/user/usr"

# Run-time checks:
#CMAKE_OPTS="${CMAKE_OPTS} -DWANT_CHECKS=on"

# Clean:
rm -rf ../usr/

if [ ${make_gfortran} -eq 1 ]; then
    echo -e "\n\n\E[1;32mMake with gfortran:\E[0m"
    make clean
    rm -rf CMakeCache.txt CMakeFiles/
    FC=gfortran cmake ${CMAKE_OPTS} -DSTOP_ON_WARNING=off ..
    make install
    if [ $? -ne 0 ]; then
	exit 1
    fi
    if [ ${clean_at_end} == 1 ]; then rm -rf ../usr/; fi
fi

if [ ${make_g95}  -eq 1 ]; then
    echo -e "\n\n\E[1;32mMake with g95:\E[0m"
    make clean
    rm -rf CMakeCache.txt CMakeFiles/
    FC=g95 cmake ${CMAKE_OPTS} ..
    make install
    if [ $? -ne 0 ]; then
	exit 1
    fi
    if [ ${clean_at_end} == 1 ]; then rm -rf ../usr/; fi
fi

if [ ${make_ifort}  -eq 1 ]; then
    echo -e "\n\n\E[1;32mMake with ifort:\E[0m"
    make clean
    rm -rf CMakeCache.txt CMakeFiles/
    FC=ifort cmake ${CMAKE_OPTS} ..
    make install
    if [ $? -ne 0 ]; then
	exit 1
    fi
    if [ ${clean_at_end} == 1 ]; then rm -rf ../usr/; fi
fi



